CREATE TABLE IF NOT EXISTS posts (
id BIGSERIAL PRIMARY KEY,
user_clerk_id TEXT NOT NULL,
content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
id BIGSERIAL PRIMARY KEY,
clerk_id TEXT NOT NULL,
first_name TEXT NOT NULL,
middle_name TEXT,
last_name TEXT NOT NULL,
gender VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
about_me VARCHAR(255)
);
